<?php
/* Start html output
 * Set a valid doctype
 */
//Print doctype to browser
echo $this->doctype();
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')->appendHttpEquiv('Content-Language', 'en-US');
?>
<html <?php echo $this->xmlnsHelper();?>>
<head>
        <?php
        //Set formatted output indent TODO: Needs tweaked
        $this->headMeta()->setIndent('    ') . "\n";
        $this->seoHelper($this->keyWords);
        //Print to browser
        echo $this->headMeta();
        //Set title seperator
        $this->headTitle()->setSeparator(' - ');

        /* Please note this will be prepended too through out the script
         * @uses Dxcore_Controller_Plugin_Pagetitle
         */
        //Set the default page title
        echo $this->siteName();
        ?>

        <base href="<?php /* This allows the server protocol to determine the base*/ echo $this->scheme .'://'. $this->host; ?>/" />
        <?php
        $this->headLink()->prependStylesheet($this->scheme.'://fonts.googleapis.com/css?family=Open+Sans+Condensed:300', 'screen');
        if($this->jQuery()->isEnabled()) {
			//$this->headLink()->prependStylesheet('/skins/default/jq-aurora/jquery-ui-1.8.23.custom.css', 'screen');
		}
		//Any remaining styles?
        $this->siteStyles();

        echo $this->headLink();
        echo $this->headStyle();
        
        $this->jQuery()->addJavascript('jQuery(function(){
                                            jQuery(".navigation").addClass("nav main");
                                       });');

        if($this->jQuery()->isEnabled() || $this->jQuery()->uiIsEnabled()) :
            if($this->scheme === 'https') {
                $this->jQuery()->setCdnSsl(true);
            }
			echo $this->jQuery();

			//$this->headScript()->appendFile('/js-src/aurora.js', 'text/javascript', null);

		endif;

        echo $this->headScript();

        ?>
</head>
<body>
    <div class="container_16">
			<div class="grid_16">
				<h1 id="branding" class="logo">
					<?php
    		        echo $this->appSettings->enableLinkLogo ? '<a href="/"><img src="/skins/'.$this->skinName.'/images/logo.png" alt="Logo" /></a>' : '<img src="/skins/'.$this->skinName.'/images/logo.png" alt="Logo" />';
    		        ?>
				</h1>
			</div>
			<div class="clear"></div>
			<div class="grid_16">
			    <?php
		        if(!IS_MOBILE)
		        echo $this->navigation()->menu();
		        ?>
			</div>
			<div class="clear"></div>
			<div class="grid_16">
				<h2 id="page-heading">System Messages will go here</h2>
			</div>
			<div class="clear"></div>
			
			<div class="box grid_16" style="padding:0;">
				<h2 style="margin:0">
					<a href="#" style="background-position:99.3% 50%" id="toggle-grid">Home Content Goes here</a>
				</h2>
			</div>
			<div class="clear"></div>
			<div id="grid" class="grid_16">
			    <div class="box home-content">
					<p>01</p>
					<?php
    	            echo $this->layout()->content;
    	            ?>
				</div>
			</div>
			<div class="clear"></div>
			
			<div class="grid_8">
			    <?php 
			    $this->appSettings->enableRelatedPages = true;
			    if($this->appSettings->enableRelatedPages) {
			    ?>
                <?php 
                    echo $this->home;
                ?>
				<?php 
				}
				?>
				<div class="box">
					<h2>
						<a href="#" id="toggle-blockquote">Blockquote</a>
					</h2>
					<div class="block" id="blockquote">
						<blockquote>
							<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
							<p class="cite">
								<cite></cite>
							</p>
						</blockquote>
					</div>
				</div>
				<div class="box">
					<h2>
						<a href="#" id="toggle-tables">Tables</a>
					</h2>
					<div class="block" id="tables">
						<table>
							<tr>
								<th>Lorem ipsum</th>
								<td>Dolor sit</td>
								<td class="currency">$125.00</td>
							</tr>
							<tr>
								<th>Dolor sit</th>
								<td>Nostrud exerci</td>
								<td class="currency">$75.00</td>
							</tr>
							<tr>
								<th>Nostrud exerci</th>
								<td>Lorem ipsum</td>
								<td class="currency">$200.00</td>
							</tr>
							<tr>
								<th>Lorem ipsum</th>
								<td>Dolor sit</td>
								<td class="currency">$64.00</td>
							</tr>
							<tr>
								<th>Dolor sit</th>
								<td>Nostrud exerci</td>
								<td class="currency">$36.00</td>
							</tr>
						</table>
						<table summary="This table includes examples of as many table elements as possible">
							<caption>An example table</caption>
							<colgroup>
								<col class="colA" />
								<col class="colB" />
								<col class="colC" />
							</colgroup>
							<thead>
								<tr>
									<th colspan="3" class="table-head">Table heading</th>
								</tr>
								<tr>
									<th>Column 1</th>
									<th>Column 2</th>
									<th class="currency">Column 3</th>
								</tr>
							</thead>
							<tfoot>
								<tr>
									<th>Subtotal</th>
									<td></td>
									<th class="currency">$500.00</th>
								</tr>
								<tr class="total">
									<th>Total</th>
									<td></td>
									<th class="currency">$500.00</th>
								</tr>
							</tfoot>
							<tbody>
								<tr class="odd">
									<th>Lorem ipsum</th>
									<td>Dolor sit</td>
									<td class="currency">$125.00</td>
								</tr>
								<tr>
									<th>Dolor sit</th>
									<td>Nostrud exerci</td>
									<td class="currency">$75.00</td>
								</tr>
								<tr class="odd">
									<th>Nostrud exerci</th>
									<td>Lorem ipsum</td>
									<td class="currency">$200.00</td>
								</tr>
								<tr>
									<th>Lorem ipsum</th>
									<td>Dolor sit</td>
									<td class="currency">$64.00</td>
								</tr>
								<tr class="odd">
									<th>Dolor sit</th>
									<td>Nostrud exerci</td>
									<td class="currency">$36.00</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="box">
					<h2>
						<a href="#" id="toggle-forms">Forms</a>
					</h2>
					<div class="block" id="forms">
						<form action="">
							<fieldset class="login">
								<legend>Login Information</legend>
								<p>
									<label>Username: </label>
									<input type="text" name="username" value="" />
								</p>
								<p>
									<label>Password: </label>
									<input type="password" name="password" />
								</p>
								<p>
									<label>Re-type Password: </label>
									<input type="password" name="password2" />
								</p>
								<input class="confirm button" type="submit" value="Confirm Availability" />
							</fieldset>
							<fieldset>
								<legend>Personal Information</legend>
								<p>
									<label>First Name: </label>
									<input type="text" name="first-name" value="" />
								</p>
								<p>
									<label>Last Name: </label>
									<input type="text" name="last-name" value="" />
								</p>
								<p>
									<label>Address: </label>
									<input type="text" name="address1" value="" />
								</p>
								<p>
									<label>Address 2: </label>
									<input type="text" name="address2" value="" />
								</p>
								<p>
									<label>City: </label>
									<input type="text" name="city" value="" />
								</p>
								<p>
									<label>State/Province: </label>
									<select name="State">
										<option value="">Select State/Province...</option>
										<option value="AL">Alabama </option>
										<option value="AK">Alaska </option>
										<option value="AB">Alberta </option>
										<option value="AZ">Arizona </option>
										<option value="AR">Arkansas </option>
										<option value="BC">British Columbia </option>
										<option value="CA">California </option>
										<option value="CO">Colorado </option>
										<option value="CT">Connecticut </option>
										<option value="DE">Delaware </option>
										<option value="DC">District of Columbia </option>
										<option value="FL">Florida </option>
										<option value="GA">Georgia </option>
										<option value="HI">Hawaii </option>
										<option value="ID">Idaho </option>
										<option value="IL">Illinois </option>
										<option value="IN">Indiana </option>
										<option value="IA">Iowa </option>
										<option value="KS">Kansas </option>
										<option value="KY">Kentucky </option>
										<option value="LA">Louisiana </option>
										<option value="ME">Maine </option>
										<option value="MB">Manitoba </option>
										<option value="MD">Maryland </option>
										<option value="MA">Massachusetts </option>
										<option value="MI">Michigan </option>
										<option value="MN">Minnesota </option>
										<option value="MS">Mississippi </option>
										<option value="MO">Missouri </option>
										<option value="MT">Montana </option>
										<option value="NE">Nebraska </option>
										<option value="NV">Nevada </option>
										<option value="NB">New Brunswick </option>
										<option value="NH">New Hampshire </option>
										<option value="NJ">New Jersey </option>
										<option value="NM">New Mexico </option>
										<option value="NY">New York </option>
										<option value="NF">Newfoundland </option>
										<option value="NC">North Carolina </option>
										<option value="ND">North Dakota </option>
										<option value="NT">Northwest Territories </option>
										<option value="NS">Nova Scotia </option>
										<option value="OH">Ohio </option>
										<option value="OK">Oklahoma </option>
										<option value="ON">Ontario </option>
										<option value="OR">Oregon </option>
										<option value="PA">Pennsylvania </option>
										<option value="PE">Prince Edward Island </option>
										<option value="PR">Puerto Rico </option>
										<option value="QC">Quebec </option>
										<option value="RI">Rhode Island </option>
										<option value="SK">Saskatchewan </option>
										<option value="SC">South Carolina </option>
										<option value="SD">South Dakota </option>
										<option value="TN">Tennessee </option>
										<option value="TX">Texas </option>
										<option value="UT">Utah </option>
										<option value="VT">Vermont </option>
										<option value="VA">Virginia </option>
										<option value="WA">Washington </option>
										<option value="WV">West Virginia </option>
										<option value="WI">Wisconsin </option>
										<option value="WY">Wyoming </option>
										<option value="YT">Yukon </option>
									</select>
								</p>
								<p>
									<label>Country: </label>
									<select name="Country">
										<option value="">Select Country...</option>
										<option value="Canada">Canada</option>
										<option value="United States">United States</option>
									</select>
								</p>
								<p>
									<label>Zip/Postal Code: </label>
									<input type="text" name="zipcode" value="" />
								</p>
								<p>
									<label>Phone Number: </label>
									<input type="text" name="phone" value="" />
								</p>
								<p>
									<label>Email Address: </label>
									<input type="text" name="email" value="" />
								</p>
								<input type="submit" value="Register" class="register-button" />
							</fieldset>
						</form>
					</div>
				</div>
			</div>
			<div class="grid_8">
			    <?php
    		    if($this->appSettings->enableSearch && !IS_MOBILE)
    		    {
            	?>
				<div class="box">
					<h2>
						<a href="#" id="toggle-search">Search</a>
					</h2>
					<div class="block" id="search">
						<?php
            		       echo new Search_Form_QuickSearch();
                		?>
					</div>
				</div>
				<?php 
    		    }
				?>
				
				<?php 
				$this->appSettings->enableHomePageGallery = false;
				if($this->appSettings->enableHomePageGallery) {
                ?>
                
                <div class="box">
					<h2>
						<a href="#" id="toggle-gallery">Gallery</a>
					</h2>
					<div class="block" id="gallery">
						<?php
            		       echo $this->media;
                		?>
					</div>
				</div>
				
				<?php 
				}
				?>
				
				<?php 
				$this->appSettings->enableHomePageLogin = true;
				if($this->appSettings->enableHomePageLogin) {
				?>
				<div class="box">
					<h2>
						<a href="#" id="toggle-login-forms">Login Forms</a>
					</h2>
					<div class="block" id="login-forms">
					<?php 
					if($this->isLogged) {
					?>
					<form action="">
							<fieldset>
								<legend>Logout</legend>
								<p>If you do not already have an account, please create a new account to register.</p>
								<input type="submit" value="Create Account" />
							</fieldset>
					</form>
					
					<?php 
					} 
					else {
                        echo new User_Form_Login();
                        echo new User_Form_Register();
					?>
					<?php 
					}
					?>
					</div>
				</div>
				<?php 
				}
				?>
				<div class="box articles">
					<h2>
						<a href="#" id="toggle-articles">Articles</a>
					</h2>
					<div class="block" id="articles">
						<div class="first article">
							<h3>
								<a href="#">Article Heading</a>
							</h3>
							<h4>Subheading</h4>
							<p class="meta">Vancouver, BC Ñ Wednesday, 23 April 2008</p>
							<a href="#" class="image">
								<img src="../../../img/photo_60x60.jpg" width="60" height="60" alt="photo" />
							</a>
							<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. <a href="#">Visit site.</a></p>
						</div>
						<div class="article">
							<h3>
								<a href="#">Article Heading</a>
							</h3>
							<h4>Subheading</h4>
							<p class="meta">Vancouver, BC Ñ Wednesday, 23 April 2008</p>
							<a href="#" class="image">
								<img src="../../../img/photo_60x60.jpg" width="60" height="60" alt="photo" />
							</a>
							<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. <a href="#">Visit site.</a></p>
						</div>
						<div class="article">
							<h1>Heading 1</h1>
							<h2>Heading 2</h2>
							<h3>Heading 3</h3>
							<h4>Heading 4</h4>
							<p class="meta">Vancouver, BC Ñ Wednesday, 23 April 2008</p>
							<a href="#" class="image">
								<img src="../../../img/photo_60x60.jpg" width="60" height="60" alt="photo" />
							</a>
							<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. <a href="#">Visit site.</a></p>
							<h5>Heading 5</h5>
							<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
							<h6>Heading 6</h6>
							<p>Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. Souvlaki ignitus carborundum e pluribus unum.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<div class="grid_16" id="site_info">
				<div class="box">
					<p>
					    <?php
		                if(isset($this->appSettings->footerText) && !empty($this->appSettings->footerText)) {
		                ?>
		                <span><?php echo $this->appSettings->footerText; ?></span>
                  <?php } ?>
			            <a>&copy;&nbsp;
				        <?php
				            $startYear = 2011; $thisYear = date('Y');
				        if ($startYear == $thisYear) :
					        echo $startYear;
				        else :
					        echo "{$startYear}-{$thisYear}";
				        endif;
				?>
				<?php echo $this->appSettings->siteName; ?>&nbsp;|&nbsp;
			    </a>
			    <span>Site by <a href="http://dirextion.com">Dire<span class="dxX">X</span>tion</a></span>
                <?php
		        if($this->appSettings->enableFooterLoginLink) { ?>
		    <?php if($this->isLogged) { ?>
                  <a href="/admin/index">ADMIN AREA</a> /
                  <a href="/user/login/logout">LOGOUT</a>
		    <?php }
		          else { ?>
		              <a href="/user/login"><?php echo $this->appSettings->footerLoginLinkText; ?></a>
		    <?php } ?>
        <?php
        }
		?>
					</p>
				</div>
			</div>
			<div class="clear"></div>
		</div>
</body>
</html>