<td id="address-info">
    <table>
    	<caption><?php echo $this->formNote('address-info-note', 'Address: (please include directions with your order)'); ?></caption>
    	<thead>
    		<tr>
    			<th><?php echo $this->formLabel('street1', 'Street 1')?></th>
    			<th><?php echo $this->formLabel('street2', 'Street 2')?></th>
    			<th><?php echo $this->formLabel('street3', 'Street 3')?></th>
    			<th><?php echo $this->formLabel('apt', 'Apt Number')?></th>
    			<th><?php echo $this->formLabel('zip', 'Zip Code')?></th>
    		</tr>

    	</thead>
    	<tbody>
    		<tr>
    			<td><?php echo $this->formText('street1'); ?></td>
    			<td><?php echo $this->formText('street2'); ?></td>
    			<td><?php echo $this->formText('street3'); ?></td>
    			<td><?php echo $this->formText('apt'); ?></td>
    			<td><?php echo $this->formText('zip'); ?></td>

    		</tr>
    		<tr>
    		    <th><?php echo $this->formLabel('city', 'City')?></th>
    		    <th><?php echo $this->formLabel('state', 'State')?></th>

    		</tr>
    		<tr>
    			<td><?php echo $this->formSelect('city', 'us', null, array('Birmingham' => 'Birmingham', 'Mt. Brook' => 'Mt. Brook', 'Homewood' => 'Homewood', 'Vestavia' => 'Vestavia')); ?></td>
    			<td><?php echo $this->formSelect('state', 'us', null, array(0 => '--', 'Al' => 'AL')); ?></td>
    			<td>&nbsp;</td>
    			<td>&nbsp;</td>
    			<td>&nbsp;</td>
    		</tr>
    		<tr>

    			<th><?php echo $this->formLabel('directions', 'Directions')?></th>
    		</tr>
    		<tr>
    			<td colspan="5"><?php echo $this->formTextarea('directions', null, array('COLS' => 80, 'ROWS' => 4)); ?></td>
    		</tr>
    	</tbody>
    </table>
</td>