<img id="map" src="/virtualtour/resources/map.png" alt="Floor Plan" usemap="#tourmap" />
<!-- map for the image -->
<map id="tourmap" name="tourmap">
    <area shape="rect" class="trigger" alt="" title="" coords="213,432,257,455" href="/tour/getimage/small/1" />
    <area shape="rect" class="trigger" alt="" title="" coords="280,402,314,433" href="/tour/getimage/small/2" />
    <area shape="rect" class="trigger" alt="" title="" coords="282,345,310,375" href="/tour/getimage/small/3" />
    <area shape="rect" class="trigger" alt="" title="" coords="314,325,343,353" href="/tour/getimage/small/4" />
    <area shape="rect" class="trigger" alt="" title="" coords="287,291,316,317" href="/tour/getimage/small/5" />
    <area shape="rect" class="trigger" alt="" title="" coords="298,264,346,285" href="/tour/getimage/small/6" />
    <area shape="rect" class="trigger" alt="" title="" coords="284,237,314,261" href="/tour/getimage/small/7" />
    <area shape="rect" class="trigger" alt="" title="" coords="281,179,311,206" href="/tour/getimage/small/8" />
    <area shape="rect" class="trigger" alt="" title="" coords="269,128,305,162" href="/tour/getimage/small/9" />
    <area shape="rect" class="trigger" alt="" title="" coords="236,82,276,116" href="/tour/getimage/small/10" />
    <area shape="rect" class="trigger" alt="" title="" coords="190,59,222,89" href="/tour/getimage/small/11" />
    <area shape="rect" class="trigger" alt="" title="" coords="140,51,175,77" href="/tour/getimage/small/12" />
    <area shape="rect" class="trigger" alt="" title="" coords="92,61,127,85" href="/tour/getimage/small/13" />
    <area shape="rect" class="trigger" alt="" title="" coords="42,75,77,115" href="/tour/getimage/small/14" />
    <area shape="rect" class="trigger" alt="" title="" coords="9,125,44,160" href="/tour/getimage/small/15" />
    <area shape="rect" class="trigger" alt="" title="" coords="4,179,31,208" href="/tour/getimage/small/16" />
    <area shape="rect" class="trigger"alt="" title="" coords="1,233,31,264" href="/tour/getimage/small/17" />
    <area shape="rect" class="trigger" alt="" title="" coords="2,289,30,320" href="/tour/getimage/small/18" />
    <area shape="rect" class="trigger" alt="" title="" coords="1,346,32,376" href="/tour/getimage/small/19" />
    <area shape="rect" class="trigger" alt="" title="" coords="1,402,33,431" href="/tour/getimage/small/20" />
    <area shape="rect" class="trigger" alt="" title="" coords="56,434,100,465" href="/tour/getimage/small/21" />
</map>

